### ISSUE TITLE
Swift 2.3 / xCode 8

### ISSUE THREAD

**Issue by Wade-BuildOtto** [meteor/cordova-plugin-meteor-webapp#16]
Some on the plugin's I am using still require Swift 2.3, their is the option to "use Legacy swift Language Version" - "YES" but I still get warnings with NSURL needing to use ! or ? and "Ambiguous use of 'dispatch_sync' (_:Block)

Seems like this should have been resolved a few versions back.

**Comment by tokn136** [comment]
Have you been able to compile it though?

**Comment by Wade-BuildOtto** [comment]
Its not compiling with these errors.

**Comment by jpmoyn** [comment]
I used to get these same errors, but when I changed the version to

`cordova-plugin-meteor-webapp@https://github.com/meteor/cordova-plugin-meteor-webapp.git#8bf95eed3f313299fc2de33658866278eea2cdc5`

I was able to successfully build the app on my device. I forget where I found the solution, but I will go looking for it and update with a reference if i can find it.

**Comment by menelike** [comment]
I've got the same problem, 3rd party libs depending on swift 2.3, latest meteor depends on swift 3.

@jpmoyn are you sure that your suggestion does not solve xcode8 problems? The commit you mentioned seems to be on swift3 already?

**Comment by lpender** [comment]
Was the history rewritten on master recently??

`cordova-plugin-meteor-webapp@https://github.com/meteor/cordova-plugin-meteor-webapp.git#8bf95eed3f313299fc2de33658866278eea2cdc5`

This worked ONCE for me and is complaining that it is "not a tree."

Looks like the commit you referenced:  "Remove Box because structs can now be stored directly" has been rewritten to `0026e0c76b2f98c3d96bee01b24f45e48cc5eb7b`

And yes, this is Swift 3 already.

It looks like `dd2d61589c27fe41c56778cb9f7bfab41a612fbd` is pre Swift3, but I'm still getting errors from that commit, even with `UseLegacySwiftVersion` set to `true`.

![image](https://cloud.githubusercontent.com/assets/1406554/23590584/bd46d19e-01b0-11e7-8613-c73d0ee5f971.png)

**Comment by lpender** [comment]
@martijnwalraven Any ideas on a commit we could use that will be Swift 2.3 compatible, for those who still need to use the `UseLegacySwiftVersion` option?

Thanks!
-Lee

**Comment by hwillson** [comment]
This has been fixed in recent versions of Meteor (>= 1.6.x).
