### ISSUE TITLE
Doc: how to retrieve a new assetbundle in native code

### ISSUE THREAD

**Issue by dagatsoin** [meteor/cordova-plugin-meteor-webapp#20]
The Android map plugin I am bulding uses meteor assets as marker image. I open them with `context.getResources().getAssets().open(filePath);`

All assets are placed in public folder (`public/icons/xxx.png`), and for a plugin to access assets, I use this path `www/application/app/icons/xxx.png`

But I can only access the initial bundle. When a new assets bundle is pushed, the plugins still displays the old assets.

So what it is the path to use for an assets from a new bundle?

**Comment by dagatsoin** [comment]
As discuss on twitter, there is no API for that.
I begin to understand how the overall process works.
I will try to do a PR with a JS methods which retrieves the bundle path. Then I will just use this method on a page reload event and send the result to my plugin.

**Comment by dagatsoin** [comment]
Finally the current asset bundle is accessible via the global variable `__meteor_runtime_config__.autoupdateVersionCordova`
So when I detect a change (on a page reload) I send the new ID to my plugin native via a cordova method. Then my plugin will adapt the path of the new asset.

@martijnwalraven do you see any potential issue with this method?

**Comment by martijnwalraven** [comment]
I think that should work. You'd be dependent on implementation details of the plugin and the asset bundle URL mappings however. These are unlikely to change anytime soon, so that may be fine.

Alternatively, you could expose `currentAssetBundle.assetForUrlPath` (see [here for use](https://github.com/meteor/cordova-plugin-meteor-webapp/blob/master/src/android/WebAppLocalServer.java#L398-L403)) and use that to get a file path.

**Comment by dagatsoin** [comment]
Yes, could reduce the dependence indeed. I put that in my todo for further improvment.
