### ISSUE TITLE
Revert to last good known version fires on external urls (Android).

### ISSUE THREAD

**Issue by dikmax** [meteor/cordova-plugin-meteor-webapp#29]
When the user navigates to the external page (like PayPal in my case) plugin runs startup timer, didn't get 'startupDidComplete' call, and then tries to revert to last good version.

I all handling should be done only on local URLs.

**Comment by hwillson** [comment]
Is this issue still happening using a recent version of Meteor (>= 1.6.x)? If so, could your please provide a small runnable reproduction that shows this happening?

**Comment by flexi-xu** [comment]
I meet the same issue with Meteor 1.7.0.5. The issue is easy to replicate.
Simply navigate to a external page on a phone by "location.replace" and wait 20 seconds. Then you will see the logs:
```
W MeteorWebApp: App startup timed out, reverting to last known good version
```

**Comment by wojtkowiak** [comment]
That's because going to another url fires the `onReset` callback from the webview which starts the startup timer. In the current arch going to external urls in the webview is not supported right now. I'm working on a solution that does not depend on the `onReset` callback so there is a chance this can help you.
