### ISSUE TITLE
ROOT_URL being replaced on iOS with the value from the server

### ISSUE THREAD

**Issue by filipenevola** [meteor/cordova-plugin-meteor-webapp#52]
Hello, I have multiple subdomains running on the same Meteor Galaxy server and I use the subdomain to identify which customer is accessing my App and with that information, I'm able to deliver specific content.

On Android, it works fine but on iOS, there is [this code](https://github.com/meteor/cordova-plugin-meteor-webapp/blob/master/src/ios/WebAppConfiguration.swift#L31) in this plugin that replaces the ROOT_URL value with the server settings.json ROOT_URL value and it breaks my way of discovering who is the current customer because on the server I have a different ROOT_URL than on each customer App.

As each customer has a different ROOT_URL I can't use the ROOT_URL from the server.

See the logs (native.app.staging.pathable.com is the customer URL and staging.pathable.com is the ROOT_URL from the server) from XCode running my Cordova App:
> Start downloading asset manifest from: manifest.json -- http://native.app.staging.pathable.com/__cordova/
....
> 2018-06-04 14:58:43.244518-0400 Pathable[285:11515] ROOT_URL seems to have changed, new: http://staging.pathable.com/, old: http://native.app.staging.pathable.com/

Is there a way to disable this code from running? Or I need to create a fork to customize this behavior? Or how can I create a pull request to make it configurable?

**Comment by brucejo75** [comment]
Hi @filipenevola,

Did you have to build a new app for each sub-domain?  Or are you able to hack a core app and modify it for each sub-domain?

I create a number of apps currently, one for each "ring" of my service.  So I can test at different levels.  I am just looking to reduce my build burden.

Any help appreciated!

Thanks!

**Comment by filipenevola** [comment]
Hi @brucejo75 actually I have a layer before my Meteor calls and subscribes to inject the actual app info so I always call the same domain because I was not able to work around the ROOT_URL issue.

But I do need to build each app individually but it's all automatic using Fastlane scripts. I don't see how, at least on my cases, to stop building different apps as the assets and store details are different.

Over the next weeks, I'm going to provide share more about my setup for Meteor apps.

**Comment by brucejo75** [comment]
Thanks @filipenevola, (I know you are a busy person and BTW: thank you for your work on Meteor!)

I think I get what you are doing.

I think the `ROOT_URL` issue could be worked around with a user visible setting (via changes to `meteor-webapp`).   I think this could be a pretty easy change.

I was looking for any way that I could take a built app and then after the fact, crack it and inject a different value for the setting to create the app. (rather than using meteor build with different values injected).  Thinking that it would take a lot less time to create the other apps.

I have been searching for APK editing tools with no luck (I am a real newb when it comes to android/iOS app development).

If there is a way to modify the app after it has been created, I would be interested in developing a PR to make `ROOT_URL` more dynamic.  I have a need for both cases.  But I am not sure it is worth to me if there are no tools to crack & modify Android and iOS apps.

**Comment by filipenevola** [comment]
I believe you would need to build a script yourself.

The first thing that comes to my mind as a plan is:
1 - Build the app1, save the content
2 - Build the app2, compare the content with a diff tool (WebStorm has a great diff tool btw) and see the differences
3 - Create a script (shell probably) to apply these differences.

I would assume it would be the app name, some ids and other basic stuff in many places. I wouldn't expect to find any hard-to-change value. 

About `ROOT_URL` it's not clear for me if you have a single backend or different ones, because if you have different ones it should be just one replace more, but if you run multiple apps using the same backend as I do then you really need a PR to make Meteor work with multiple root URLs.
